### ISSUE TITLE
1.9 Texture Packs invalid

### ISSUE THREAD

**Issue by BrisingrAerowing** [cyanobacterium/Minecraft_Mineralogy#10]
The files in the texture packs for 1.9 are under a subfolder, which makes MC not detect them. The files need to be moved up one directory level in the archive to work.

e.g. the x128 archive looks like:

- Mineralogy-texture-pack-x128.zip
-- x128
--- \*all other files\*

The x128 folder needs to be removed and its contents moved to the root of the archive.

**Comment by jriwanek** [comment]
The 1.10.x Resource packs should work with 1.9.x too. I'll give it a test soon to make sure though and I'll also fix the older file releases.

**Comment by jriwanek** [comment]
FIxed and retagged as  rp1.9-2
