### ISSUE TITLE
[FREQ] Bulk storage blocks of sulphur, gypsum, etc

### ISSUE THREAD

**Issue by Syndaryl** [cyanobacterium/Minecraft_Mineralogy#11]
These drop in large quantities. Gypsum in particular is difficult to deal with, as I have tunnel through large veins of it to get anywhere, but a similar comment applies to the other powder minerals.

The ability to craft these into 3x3 packed blocks (like redstone and lapis lazuli) would be really appreciated. They'd primarily be decorative blocks, but being able to use the hammer to smash them back into the powder makes them also storage. 

Even without being able to reverse them back into powder, the decorative blocks would be neat. Making a statue out of gypsum seems sort of appropriate, and decorating my nether portal with blocks of sulphur really appeals to me.

**Comment by jriwanek** [comment]
Gypsum, Sulfur, Nitrate and Phosphorous are implemented in my local branch, Will upload to github once I've finished testing, and to curse once I've reimplemented slabs.

**Comment by Syndaryl** [comment]
Hurray!

**Comment by SkyBlade1978** [comment]
Thanks, looking forward to it :)
