### ISSUE TITLE
High res texture pack sandstone not working

### ISSUE THREAD

**Issue by MeinoHax** [cyanobacterium/Minecraft_Mineralogy#14]
In the high resolution texture pack sandstone still has the low resolution texture  from before, however the files for high res sandstone are there, i dont know why they won't show up in the game tho...

I'm using latest minecraft forge for minecraft 1.10.2

**Comment by jriwanek** [comment]
Will be fixed in next release.

**Comment by SkyBlade1978** [comment]
I'm really pleased to know you're still working on these mods, thanks :)

Are you just doing patches or might a 1.11.x build be in the pipeline?

**Comment by jriwanek** [comment]
1.11.x, 1.12,x, 1.13.x (when it's out), and patches for earlier versions too.

**Comment by SkyBlade1978** [comment]
Thanks very much, are there any time consuming coding tasks I can help with?

I've done a lot of c# but some Java

If there isn't anything in particular, I was considering seeing about adding walls (and sending a pull request if it works) in the same way steps are added (in addStoneType) unless you've already doing that or there was some technical reason they aren't there, like maybe the textures would look weird when wrapped around a wall?

I was also thinking that the hard coded registrations of stone types could be put in a json block in a config file then read out and iterated over calling addStoneType which unless theres some reason why its a bad idea might be an interesting refactor to do..

**Comment by jriwanek** [comment]
@SkyBlade1978 Come visit https://discordapp.com/invite/wUHHBVA (Discord invite) and chat with me and the rest of the team, help is *always* welcomed, as are ideas and input.

**Comment by jriwanek** [comment]
Also, I might see about walls in the morning. (Should be easy to implement)
