### ISSUE TITLE
Mineralogy 2.4.1 right clicking half slab with empty hand crashes game.

### ISSUE THREAD

**Issue by technolem** [cyanobacterium/Minecraft_Mineralogy#3]
Exactly what it says. Tested with schist and slate.

**Comment by cyanobacterium** [comment]
Oh dear. It must be checking if you are holding another half-slab and crashing with a null pointer exception. I'll fix that today.

**Comment by cyanobacterium** [comment]
Fix implemented in version 2.5.0.

**Comment by technolem** [comment]
It works, thanks!
