### ISSUE TITLE
Side Effects With Thaumcraft

### ISSUE THREAD

**Issue by magerooster** [cyanobacterium/Minecraft_Mineralogy#7]
The issue: Thaumcraft's Outer Lands world gets mineralogized, which mostly ruins the dimension's special world gen rules.

It probably does this to other special mod dimensions, too, but I haven't encountered any yet.

My suggestion for a solution: Provide a config option for blacklisting dimension IDs for Mineralogy to ignore (and optionally add dimension -42 to it by default)

A fancier solution would be to figure out whether normal world generation is happening and figure out dimensions to skip yourself, but I'm honestly not sure how reliable a detection is possible.

**Comment by cyanobacterium** [comment]
You're right. There's a bug that makes it apply to all dimensions when it sould only apply tot he overworld. I'll fix that later this week.

**Comment by cyanobacterium** [comment]
Sorry for the delay. Fixed in version 2.6.1
