### ISSUE TITLE
[CURSE] Can't use Curse Client to download

### ISSUE THREAD

**Issue by AlvarOsO** [cyanobacterium/Minecraft_Mineralogy#8]
The default Curse download is the Resource Pack, so the Curse Client downloads it, instead of the mod file.

**Comment by cyanobacterium** [comment]
I've never used the Curse Client (I didn't even know such a thing existed until very recently) and I don't know how to specify which file is the mod file. Do you know where I could find the relevant instructions on how to fix this?

**Comment by AlvarOsO** [comment]
[Well, i found this:](http://www.curseforge.com/knowledge-base/105-submitting-a-project-part-2-submit-a-file)
"Release Type: Release, Beta and Alpha all act slightly differently. Release files sync to Curse.com and eventually to the Curse Client. These are the files that will auto download when a user clicks the default download button on a project. Beta files sync to Curse.com but will not sync to the client unless the user chooses to receive Beta files. Alpha files do not sync to Curse.com and are only available on CurseForge.com. More on file types can be found here."
So, it seems like it automatically selects the lastest Release download as the default one, so one way to go would be mark all the resource packs as Alpha type.
[Or make them additional downloads of the mod, instead of them beign their own.](http://www.curseforge.com/knowledge-base/103-file-types-what-do-they-mean)

**Comment by cyanobacterium** [comment]
I tried to make the texture packs be add-on files to the mod file, but Curse refused to upload them, so I archived the texture packs and added a link to the Github releases page in the description. I guess that will fix it.
