### ISSUE TITLE
Block names ends with .name

### ISSUE THREAD

**Issue by AfterRebelion** [cyanobacterium/Minecraft_Mineralogy#9]
Minecraft 1.9
Forge: 12.16.0.1865
Mineralogy: 3.0.0
[Every block in the mod has a .name at the end of their display name](https://cloud.githubusercontent.com/assets/559819/14806445/58ce6fa8-0b73-11e6-918d-1cb81cd8d3bf.png)

**Comment by cyanobacterium** [comment]
Oops. I'll fix that and update soon.

**Comment by cyanobacterium** [comment]
Fixed in version 3.0.1. Thank you for reporting this issue.
